#!/usr/bin/env node
// build.js — single source of truth for both project shapes.
//
// Problem this solves (see review report, items 3 & 4):
//   - game.js / audio.js / input.js were loaded as three separate top-level
//     <script> tags relying on browsers sharing top-level let/const across
//     <script> tags on the same page. That works, but it's an implicit,
//     load-order-dependent mechanism with no explicit boundary, and it
//     silently breaks if the files are ever loaded as modules, bundled by
//     a different tool, or reordered.
//   - neon-beat.html / neon-beat-editor.html (monolithic single-file builds)
//     were hand-maintained copies of the modular source and had already
//     diverged from it.
//
// What this script does:
//   1. Bundles js/game/{audio,game,input}.js into ONE explicit IIFE (plus the
//      shared/* helper scripts, which were already safe globals-only utility
//      files) → js/game/bundle.js. game.html loads this single file instead
//      of three loosely-coupled ones.
//   2. Bundles js/editor/editor.js (already self-contained in its own IIFE)
//      with the shared/* helpers → js/editor/bundle.js. editor.html loads it.
//   3. Regenerates neon-beat.html and neon-beat-editor.html by taking
//      game.html/editor.html as templates and inlining the bundled JS + CSS.
//      Since both shapes are now generated from the same bundles, they
//      cannot drift from the modular source or from each other again.
//
// Usage: node build.js   (run from the project root, no dependencies needed)

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');
const write = (p, content) => fs.writeFileSync(path.join(ROOT, p), content);

const SHARED_FILES = [
  'js/shared/storage.js',
  'js/shared/song-db.js',
  'js/shared/chart-format.js',
  'js/shared/speed-scroll.js',
  'js/shared/canvas-utils.js',
  'js/shared/gameplay.js',
];

function banner(label) {
  return `// ===== ${label} (generated by build.js — do not edit directly) =====\n`;
}

function buildSharedJs() {
  return SHARED_FILES.map((f) => banner(f) + read(f)).join('\n');
}

function buildGameBundle() {
  const shared = buildSharedJs();
  // audio.js, game.js, input.js share one explicit closure instead of
  // relying on cross-<script>-tag global lexical scope (report item 2.2).
  const engine = ['js/game/audio.js', 'js/game/game.js', 'js/game/input.js']
    .map((f) => banner(f) + read(f))
    .join('\n');
  return shared + '\n' + banner('game engine (audio.js + game.js + input.js), wrapped together')
    + '(function(){\n' + engine + '\n})();\n';
}

function buildEditorBundle() {
  const shared = buildSharedJs();
  // editor.js already wraps itself in its own IIFE — just append it.
  const editor = banner('js/editor/editor.js') + read('js/editor/editor.js');
  return shared + '\n' + editor;
}

function replaceScriptBlock(html, scriptSrcs, replacementTag) {
  // Removes a contiguous run of <script src="...">, then inserts
  // replacementTag where the first one was.
  const lines = html.split('\n');
  let firstIdx = -1;
  const out = [];
  for (let i = 0; i < lines.length; i++) {
    const isTargeted = scriptSrcs.some((src) => lines[i].includes(`src="${src}"`));
    if (isTargeted) {
      if (firstIdx === -1) firstIdx = out.length;
      continue; // drop this line
    }
    out.push(lines[i]);
  }
  if (firstIdx === -1) throw new Error('No matching <script> tags found to replace');
  out.splice(firstIdx, 0, replacementTag);
  return out.join('\n');
}

function inlineStylesheets(html, cssHrefs) {
  for (const href of cssHrefs) {
    const css = read(href);
    const linkTag = `<link rel="stylesheet" href="${href}">`;
    if (!html.includes(linkTag)) throw new Error(`Stylesheet link not found for ${href}`);
    html = html.replace(linkTag, `<style>\n${css}\n</style>`);
  }
  return html;
}


function buildMonolith(templateHtml, cssHrefs, scriptSrcs, bundleJs) {
  let html = inlineStylesheets(templateHtml, cssHrefs);
  html = replaceScriptBlock(html, scriptSrcs, '<script>\n' + bundleJs + '\n</script>');
  return html;
}

function main() {
  const gameScriptSrcs = [
    'js/shared/storage.js', 'js/shared/song-db.js', 'js/shared/chart-format.js',
    'js/shared/speed-scroll.js', 'js/shared/canvas-utils.js',
    'js/game/audio.js', 'js/game/game.js', 'js/game/input.js',
  ];
  const editorScriptSrcs = [
    'js/shared/storage.js', 'js/shared/song-db.js', 'js/shared/chart-format.js',
    'js/shared/speed-scroll.js', 'js/shared/canvas-utils.js',
    'js/editor/editor.js',
  ];

  // Read the original (still-modular, 8-script-tag) templates FIRST — both
  // outputs below are derived from these, and game.html/editor.html get
  // overwritten later in this function.
  const gameTemplate = read('game.html');
  const editorTemplate = read('editor.html');

  const gameBundle = buildGameBundle();
  const editorBundle = buildEditorBundle();
  write('js/game/bundle.js', gameBundle);
  write('js/editor/bundle.js', editorBundle);
  console.log('wrote js/game/bundle.js, js/editor/bundle.js');

  // Monolithic single-file builds, generated fresh from the same bundles —
  // can no longer drift from the modular source (report item 4).
  const neonBeat = buildMonolith(
    gameTemplate, ['css/shared.css', 'css/game.css'], gameScriptSrcs, gameBundle
  );
  const neonBeatEditor = buildMonolith(
    editorTemplate, ['css/shared.css', 'css/editor.css'], editorScriptSrcs, editorBundle
  );
  write('neon-beat.html', neonBeat);
  write('neon-beat-editor.html', neonBeatEditor);
  console.log('wrote neon-beat.html, neon-beat-editor.html');

  // Modular game.html / editor.html: load the single bundle instead of
  // 6-8 separate <script> tags (fixes the fragile load-order coupling live,
  // not just in the generated monolith).
  const gameHtml = replaceScriptBlock(
    gameTemplate, gameScriptSrcs, '<script src="js/game/bundle.js"></script>'
  );
  const editorHtml = replaceScriptBlock(
    editorTemplate, editorScriptSrcs, '<script src="js/editor/bundle.js"></script>'
  );
  write('game.html', gameHtml);
  write('editor.html', editorHtml);
  console.log('updated game.html, editor.html to load the bundles');
}

main();
